# Generated by Django 4.1.7 on 2023-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=15)),
                ('descripcion', models.TextField(max_length=25)),
                ('dificultad', models.TextField(max_length=7)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
