# Generated by Django 4.1.7 on 2023-05-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registro_lol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeon',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campeon',
            name='descripcion',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='campeon',
            name='dificultad',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='campeon',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
