# Generated by Django 4.1.7 on 2023-05-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_lol', '0002_campeon_publisher_alter_campeon_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='campeones'),
        ),
    ]
